### ISSUE TITLE
Does not work if Moodle is in a subdirectory

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-local_session_keepalive#1]
https://github.com/moodleuulm/moodle-local_session_keepalive/blob/master/amd/src/keepalive.js

Has the same problem as reported in the other plugin https://github.com/moodleuulm/moodle-local_maintenance_livecheck/issues/1

**Comment by abias** [comment]
Oh, shame on me, I missed that. Thanks for spotting, David - this is fixed now in 9e41e3b476321cdcfcadcc0d3b342db6ae9fe94b
