### ISSUE TITLE
String setting_keepaliveinterval_desc must not define the URL like this

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-local_session_keepalive#2]
Same problem as in https://github.com/moodleuulm/moodle-local_profiletheme/issues/6

**Comment by abias** [comment]
Thanks, David, for pointing this out. Once again, I missed this possibility of running Moodle in a subdir.

Fixed in c7ed85c3d07a67409668e05e39fec22b0a0a9fca.
