### ISSUE TITLE
Moodle 3.1 compatibility

### ISSUE THREAD

**Issue by peterkhl** [moodleuulm/moodle-local_session_keepalive#5]
Sorry for posting my question here. I am really interested whether your pluging works  correctly  with moodle 3.1?
Petr.

**Comment by abias** [comment]
Hi Petr,

please see https://github.com/moodleuulm/moodle-local_session_keepalive/blob/master/README.md#moodle-release-support for a general answer. And as a specific answer, I am quite sure that the plugin does not use any features from 3.2+, so just give it a try.

Thanks,
Alex

**Comment by peterkhl** [comment]
Thank you! I'll try.
